<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <StartupObject>FractalPainting.UI.Program</StartupObject>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <None Remove=".gitignore"/>
    <Compile Remove="*/*.Initial.*"/>
    <None Include="*/*.Initial.*"/>
    <Compile Update="UI\MessageBox.axaml.cs">
      <DependentUpon>MessageBox.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.6"/>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.6"/>
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.6"/>
    <PackageReference Include="bodong.Avalonia.PropertyGrid" Version="11.0.5.1"/>
    <PackageReference Include="bodong.PropertyModels" Version="11.0.5.1"/>
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="FluentAssertions" Version="6.12.2"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
    <PackageReference Include="Ninject" Version="3.3.6"/>
    <PackageReference Include="Ninject.Extensions.Conventions" Version="3.3.0"/>
    <PackageReference Include="Ninject.Extensions.Factory" Version="3.3.3"/>
    <PackageReference Include="NUnit" Version="4.2.2"/>
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1"/>
  </ItemGroup>
</Project>
